### ISSUE TITLE
 Add a list all button to the home page

### ISSUE THREAD

**Issue by maoyiluo** [NYU-DevOps-Fall19-Payments-Team/payments#117]
**As a** customer
**I need** a list all button to show all the payments
**So that** the homepage won't show all the payments unless I press the button

**Assumptions:** 
* Add a button with ID `list_all-btn` and wrap the `list all` part into `$('list_all-btn).click()`
* Add `when I click the "list_all" button` to the each scenario that need see the display card.

**Acceptance Criteria:**
```
Given the step as before
Then the behave test still passes.
```

**Comment by dqrjz** [comment]
Closed by pr #119
