### ISSUE TITLE
Create a NoSQL database

### ISSUE THREAD

**Issue by maoyiluo** [NYU-DevOps-Fall19-Payments-Team/payments#17]
**As a**Developer
**I need** to set up a NoSQL database
**So that** figure out what's the difference between NoSQL and SQL.

**Assumptions:** 
*We are using MongoDB
*We are using a library for flask to work with MongoDB
*We are using some method to measure the performance of the database.

**Acceptance Criteria:**
```
When we send any kind of data or request we have already implemented for MySQL
Then return the same result as MySQL
```

**Comment by amshirif** [comment]
We've decided to go ahead with Postgres. An issue has been made and completed.
