### ISSUE TITLE
Set up the table in model.py

### ISSUE THREAD

**Issue by maoyiluo** [NYU-DevOps-Fall19-Payments-Team/payments#33]
**As a** developer
**I need** to set up the model of our table `payments`
**So that** everyone in our team can work on the API routes.

**Assumptions:** 
Here are the columns of the table:
- id [integer] primary key
- customerId [integer]
- orderId [integer]
- info [JSON]
- type [String]
- avaiable [boolean]

**Acceptance Criteria:**
```
When we initialize our database
Then we can see the table with these columns in our database
```

**Comment by dqrjz** [comment]
Add an "Available" column.

**Comment by maoyiluo** [comment]
> Add an "Available" column.

Added to the list.
