### ISSUE TITLE
Create a BDD ".feature" file and accompanying ".steps" file to test the API from the outside in

### ISSUE THREAD

**Issue by dqrjz** [NYU-DevOps-Fall19-Payments-Team/payments#85]
**As a** developer
**I need** a Behavior Driven Development test suite
**So that** I can run automated testing before deploying to Production

**Assumptions:** 
* Create a BDD _.feature_ file and accompanying _.steps_ file
* Write the feature using _Gherkin_ syntax that is understood by the behave tool
* There should be at least 7 Scenarios in the feature file, one for each of Create, Read, Update, Delete, List, Query, and Action
* Use Selenium to conduct UI testing

**Acceptance Criteria:**
```
Given I have set up the BDD automated testing using Selenium
When I run the test using "behave"
Then all scenarios are green (passing)
```

**Comment by amshirif** [comment]
Assignments:
Amir- Update, Delete
Alex- Action
Maoyi- Create, Read
Zheng- List, Query
